name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Pages
      uses: actions/configure-pages@v1

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./ 

    - name: Deploy
      id: deployment
      uses: actions/deploy-pages@v1
